
name: Security Checks
on: [pull_request, push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
    
    steps:
       - uses: actions/checkout@v1  
       - name: Building Docker Node-Goat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach
         
       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.4.0
         with:
           # Target URL
           target: "http://localhost:4000"
           fail_action: true
